import Link from 'next/link'
import { Navigation } from '../components/navBar'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <head>
        <title>Vito Stationary Shop</title>
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
